name: Pizza Planet CI

on:
  pull_request:
    branches:
      - main

jobs:
  CI-Pizza-Planet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"

      - name: Install Requirements
        run: make install-requirements

      - name: Run tests
        run: make tests

      - name: Build coverage file
        run: make coverage_file

      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
